### ISSUE TITLE
Uploads seem to fail randomly

### ISSUE THREAD

**Issue by fptwm** [Bynder/bynder-php-sdk#33]
We have a cronjob that is uploading assets to a bynder instance each night, which has been running fine for nearly two years. Lately though, it seems that each night random items fail. We get the following stack trace:
```
[Exception] Caught Error: Cannot use object of type GuzzleHttp\Psr7\Response as array
>Stacktrace:
# 1 /opt/twm06-manja/web/vendor/bynder/bynder-php-sdk/src/Bynder/Api/Impl/Upload/FileUploader.php:336 yield $this->pollStatusAsync(['items' => $finalizeResponse['importId']], $delay);
# 2 [internal]: Bynder\Api\Impl\Upload\FileUploader->pollStatusIterator( Object(GuzzleHttp\Psr7\Response) )
# 3 /opt/twm06-manja/web/vendor/guzzlehttp/promises/src/EachPromise.php:79 Generator->rewind( )
# 4 /opt/twm06-manja/web/vendor/bynder/bynder-php-sdk/src/Bynder/Api/Impl/Upload/FileUploader.php:319 GuzzleHttp\Promise\EachPromise->promise( )
# 5 /opt/twm06-manja/web/vendor/bynder/bynder-php-sdk/src/Bynder/Api/Impl/Upload/FileUploader.php:139 Bynder\Api\Impl\Upload\FileUploader->hasFinishedSuccessfullyAsync( Object(GuzzleHttp\Psr7\Response) )
# 6 /opt/twm06-manja/web/vendor/guzzlehttp/promises/src/Promise.php:204 Bynder\Api\Impl\Upload\FileUploader->Bynder\Api\Impl\Upload\{closure}( Object(GuzzleHttp\Psr7\Response) )
# 7 /opt/twm06-manja/web/vendor/guzzlehttp/promises/src/Promise.php:153 GuzzleHttp\Promise\Promise::callHandler( 1, Object(GuzzleHttp\Psr7\Response), null )
# 8 /opt/twm06-manja/web/vendor/guzzlehttp/promises/src/TaskQueue.php:48 GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}( )
# 9 /opt/twm06-manja/web/vendor/guzzlehttp/promises/src/Promise.php:248 GuzzleHttp\Promise\TaskQueue->run( true )
#10 /opt/twm06-manja/web/vendor/guzzlehttp/promises/src/Promise.php:224 GuzzleHttp\Promise\Promise->invokeWaitFn( )
#11 /opt/twm06-manja/web/vendor/guzzlehttp/promises/src/Promise.php:269 GuzzleHttp\Promise\Promise->waitIfPending( )
#12 /opt/twm06-manja/web/vendor/guzzlehttp/promises/src/Promise.php:226 GuzzleHttp\Promise\Promise->invokeWaitList( )
#13 /opt/twm06-manja/web/vendor/guzzlehttp/promises/src/Promise.php:62 GuzzleHttp\Promise\Promise->waitIfPending( )
#14 /opt/twm06-manja/web/ext/ui_cpmgmt/export_modules/bynder/lib/inc_bynder_export_service_client.php:157 GuzzleHttp\Promise\Promise->wait( )
```
We did make slight changes to our code some time ago, i.e., we do not send items through the waiting room and do not relate the assets to each other anymore. However, as the same item with the same metadata usually succeeds on the next day, it doesn't seem to be an issue on our side. Furthermore, there does not seem to be any correlation between the error being triggered and the type of file we are uploading. We send JSON, TIF and XLSX files, and have seen all of those fail.

We are using version 1.0.9 on PHP 7.3.

**Comment by githuib** [comment]
Hi @fptwm would it be possible for you to upgrade to the most recent version of our SDK? I couldn't reproduce it there so that might be a straightforward solution.

**Comment by fptwm** [comment]
Upgrading to the newest version requires some changes to our code, and since OAuth 1.0 is no longer supported, we'd also need to change authentication. Can we use our existing OAuth 1.0 tokens for OAuth 2.0? My understanding so far is that this requires a different/new permanent access token - how do we get/generate one?

**Comment by githuib** [comment]
I see. I would recommend to switch to using OAuth 2.0 or permanent tokens. For more information how to create and use those, I'd like to refer to these knowledge base items:
https://support.bynder.com/hc/en-us/articles/360013875180-Create-your-OAuth-Apps
https://support.bynder.com/hc/en-us/articles/360013875300-Permanent-Tokens

I hope this helps, please let me know if you have any more questions regarding this.

**Comment by fptwm** [comment]
While we are working on upgrading to the latest SDK version, the error seems to have changed lately. In case you want to investigate this, we now get a 404 error for some seemingly random files:

```
Client error: `POST https://dam.cchellenic.com/api/v4/upload/.Ekx.1ngG1pF4fZRl.w4DcgQ2514LPsnlrd_nzzCF32IYdD7_G_9aNQk5qMd0tjGs8aT4UUlxSGBZU4s39psd3bapaKUN2SZItXRZbdzBOkNVR7Wl1J.zI.4QLEUuSL_/` resulted in a `404 Not Found` response:
<html><head><title>Error</title></head><body>Not Found</body></html>
```

**Comment by TimBloembergen** [comment]
Hi @fptwm We have a bug currently which concerns the uploadid's. When uploadid's lead with a . the upload will result in an error like the one you received. 
I think we can close this ticket and I will keep you informed regarding the progress on the bug fix in the support ticket that we have.

**Comment by WouterToering** [comment]
Hey @fptwm,

We've just released version 2.1.3 to packagist which works around the issue with the uploadId's starting with a dot. Could you please update and verify this particular issue does not occur anymore?

**Comment by fptwm** [comment]
Uploading (with the old SDK) has worked ok in the last weeks. We will still be updating to 2.1.5 in the coming weeks. It seems that this is fixed and I'll close this issue. If for some unlikely reason we still encounter problems, I'll update/re-open this issue.
